# rebind prefix to C-a
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# set base-index to 1
set -g base-index 1
setw -g pane-base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# allows for mouse support
set -g mouse on

# prefix + space to jump back to prev window
bind Space last-window

# bar settings
set-option -g status-justify left
set -g status-left-length 85
set -g status-style 'bg=default,fg=#fff4d2'
set-option -g status-right '#[bg=#d8a657 , fg=#000000,bold] #S '
set-option -g status-left ''

set -g window-status-format "#[fg=#ebdbb2,bg=#303030,bold]  #I #[fg=#ebdbb2,bg=#404040,bold] #W "
set -g window-status-current-format "#[fg=#000000,bg=#d8a657,bold]  #I #[fg=#000000,bg=#83a598 ,bold] #W "

set -g message-style bg=#d8a657,fg=#1d1d1d,bold
set -g message-command-style bg=#1d1d1d,fg=#d8a657,bold

set -g pane-active-border-style fg=#8ec07c
set -g pane-border-style fg=#555555

# plugins
set -g @plugin 'tmux-plugins/tpm'

# tmux plugins
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux session after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions after every 15 mins

# plugins settings
set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-strategy-nvim 'session'


# initializing the plugin manager 
run '/usr/share/tmux-plugin-manager/tpm' # Need to be kept in the very bottom
